name: flutter_app_cliente
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter




  http: any
  progress_hud: ^1.1.0
  url_launcher: ^5.4.2
  google_maps_flutter: ^0.5.24+1




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
